copy build\bin\ironfist.exe "C:\Program Files (x86)\HEROES2"
copy build\bin\editor.exe "C:\Program Files (x86)\HEROES2"
copy build\ironfist.agg "C:\Program Files (x86)\HEROES2\DATA"
copy data\creatures.xml "C:\Program Files (x86)\HEROES2\DATA"
copy maps\*.mx2 "C:\Program Files (x86)\HEROES2\MAPS"
copy maps\*.mp2 "C:\Program Files (x86)\HEROES2\MAPS"
copy maps\*.mx2.lua "C:\Program Files (x86)\HEROES2\SCRIPTS"
copy maps\modules\*.* "C:\Program Files (x86)\HEROES2\SCRIPTS\MODULES"
